name             "drupal-codeception"
maintainer       "Alex knoll"
maintainer_email "Alex@AlexKnoll.com"
license          "Apache 2.0"
description      "Installs/configures codeception and runs tests"
version          "0.1.0"
recipe           "drupal-codeception::default", "Installs/configures codeception"
